### ISSUE TITLE
set_file_path error

### ISSUE THREAD

**Issue by nsheff** [epigen/open_pipelines#2] opened 2017-08-09 13:51 UTC
Reported by @mtugrul

I was not able to run chipseq.py and atacseq.py in looper. The following error comes, I looked into the corresponding lines but did not understand why. Any help?

chipseq:
```
Traceback (most recent call last):
File "/home/mtugrul/software/pipelines/pipelines/chipseq.py", line 755, in
sys.exit(main())
File "/home/mtugrul/software/pipelines/pipelines/chipseq.py", line 473, in main
sample.set_file_paths()
File "/home/mtugrul/software/pipelines/pipelines/chipseq.py", line 78, in set_file_paths
super(ChIPseqSample, self).set_file_paths()
TypeError: set_file_paths() takes exactly 2 arguments (1 given)
```
atacseq:
```
Traceback (most recent call last):
File "/home/mtugrul/software/pipelines/pipelines/atacseq.py", line 723, in
sys.exit(main())
File "/home/mtugrul/software/pipelines/pipelines/atacseq.py", line 456, in main
sample.set_file_paths()
File "/home/mtugrul/software/pipelines/pipelines/atacseq.py", line 54, in set_file_paths
super(ATACseqSample, self).set_file_paths()
TypeError: set_file_paths() takes exactly 2 arguments (1 given)
```

ok, it looks like this problem is due to new looper versions. When I install looper v0.5, it seems to be running now. I tried with all other dev versions of looper v0.6, but no success! I will stick to v0.5 for now, but this should be solved in long term.

**Comment by nsheff** [comment] 2017-08-09 13:53
yeah, looks like this was changed in epigen/looper@fa7989e0456cad1934fa183c6a9a4ea615f5dea3

when working on project/sample separation. Error derived, for example, from:

https://github.com/epigen/open_pipelines/blob/bbbb2d07e5ab3ae51c681913ad2d06e7866d16cc/pipelines/atacseq.py#L54

Letting @vreuter know -- but I think it's a simple fix in `open_pipelines`

**Comment by vreuter** [comment] 2017-08-09 14:46
Yeah, this was probably sufficiently significant to warrant a major version designation. I think the changes aren't terribly involved, but I think there are a couple to make on both the implementation and application sides of `Sample`. And actually, it may be possible to confine them to the implementation side in `looper`.

Right now, `set_file_paths` on `Sample` needs to be passed a `Project` reference. But, with the current way in which the `prj` attribute on `Sample` is serialized and made available to a pipeline, the data contained within that attribute's value may be insufficient to successfully execute the `set_file_paths` method if that value is passed as the argument to the method's `project` parameter.

I think there are two broad approaches to solve this, within which more desirable/favorable implementation options may become apparent. We could include a greater extent of the `Project` data that's stored during serialization of the `prj` attribute (actually, I think this should be done regardless of how it's then used/handled). Then, pipelines could be responsible for knowing about these things (as sections, e.g. `metadata` and `trackhubs`, or other suitably grouped and named data sections, or as individual attributed, e.g. `output_dir`, `results_subdir`, etc.). Such items would be provided as parameters and accepted as arguments to `set_file_paths`. Alternatively, `Sample` could assume the availability of such sections/attributes on itself, then use that assumption in `set_file_paths`. Discussion would then be open for appropriate failure severity (exception vs. error message vs. warning message), and for completeness of failure (a la carte setting of file paths for data elements that are present, or wholesale failure if anything's missing).

While the second of those options implies a stronger bond between `Project` and `Sample`, it seems like there's more comfort with this way, and that it'd be less disruptive to existing usage patterns, entailing changes of lesser extent.

**Comment by afrendeiro** [comment] 2017-08-14 12:09
@mtugrul, up to looper 0.6.0-rc1 there's no problem - I'm still using this by the way.

This would be easy to fix on the pipeline side but I'd prefer if looper would allow one instantiating and working with a single isolated Sample from its serialized yaml without help from its Project.

The whole point of using sample-type-specific objects inside a pipeline has become a bit overkill since everything is specified in the sample config and any path is easily built from those. However one might want to use a similar approach (serializing/reinstantiating a single Sample) in other non-pipeline related use-cases - I do use these objects all the time but I usually instantiate all samples at the Project level anew.

**Comment by vreuter** [comment] 2017-08-15 19:22
Just a note...until the next `looper` release, the full fix for this will depend on the `dev` branch of `looper`. https://github.com/epigen/open_pipelines/pull/3 will solve this specific issue, but a different one will arise within `set_file_paths` without the `dev` version of `looper`.

**Comment by afrendeiro** [comment] 2017-08-16 11:54
Cool, thanks - will test soon.

**Comment by nsheff** [comment] 2017-08-20 01:25
@afrendeiro why are you still using 0.6.0-rc1 ? :wink: 

> I'd prefer if looper would allow one instantiating and working with a single isolated Sample from its serialized yaml without help from its Project.

I agree -- @vreuter does that jive with your thought for how `set_file_paths` will work? You had previously been working on severing the Project/Sample connection anyway, right?

> one might want to use a similar approach (serializing/reinstantiating a single Sample) in other non-pipeline related use-cases

But why not then just do the same as in the pipeline? I still see utility in the sample-type-specific objects inside a pipeline. It's not necessary, sure, but it can be convenient...

**Comment by vreuter** [comment] 2017-08-20 04:14
I'm confused...from where/whom is the context you're quoting...I thought I was the one pushing hardest for `Sample`/`Project` separation? Currently, the `prj` attribute isn't actually a `Project`; it's an `AttributeDict` containing the `Project` sections germane to setting file paths. My preference on the method signature is vanishingly weak, so I'm totally fine with reverting it to zero-arg. The entirety of my concern is constraining the complexity of a `Sample` (i.e., limiting its access to `Project` data to the bare necessities).

I agree about the sample subtypes' convenience, and while it seems that currently they're mainly used for specific path attributes, I don't see a reason why that would be the only reason to implement one. It feels like pulling that hook would strip flexibility without a clear upside.

Hopefully that answered the intended questions/solicitations for opinion...sorry for any confusion; I just wasn't completely sure what was being suggested/asked.

**Comment by nsheff** [comment] 2017-08-21 11:14
> I'm confused...from where/whom is the context you're quoting.. 

@afrendeiro's most recent comment in this thread:

>This would be easy to fix on the pipeline side but I'd prefer if looper would allow one instantiating and working with a single isolated Sample from its serialized yaml without help from its Project.

From you:

> I was the one pushing hardest for Sample/Project separation

Yeah. I think I misread your earlier comment.

Probably adding project-level variables to sample objects is less disruptive and satisfies @afrendeiro's point. 

What about adding a "project_config" attribute to Samples that points at the project yaml file that was used to create it? then re-creating the project if needed?

**Comment by vreuter** [comment] 2017-08-21 13:06
Recreating the `Project` would provide a `Sample` with access to all of its siblings.
The `Project` variables are already attached, the signature just requires that their container--an `AttributeDict` referenced by attribute `prj`--be passed to the `set_file_paths` method. To me it seems that the change needed is to simply have the `set_file_paths` method assume the existence of this attribute and use that, rather than requiring an argument.

**Comment by afrendeiro** [comment] 2018-01-26 16:04
The current master branch works around this with looper 0.7.2 and pypiper 0.6.
Since the issue is on the error in the context of the pipelines I'm closing this.

**Closed as completed by afrendeiro** 2018-01-26 16:04 UTC
